site_name: Trivy
site_url: https://aquasecurity.github.io/trivy/
site_description: A Simple and Comprehensive Vulnerability Scanner for Containers and other Artifacts, Suitable for CI
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/trivy
edit_uri: ""

nav:
  - Getting Started: 
      - Overview: index.md
      - Installation: getting-started/installation.md
      - FAQ: getting-started/faq.md
  - Tutorials:
      - Overview: tutorials/overview.md   
      - CI/CD:
          - Overview: tutorials/integrations/index.md
          - GitHub Actions: tutorials/integrations/github-actions.md
          - CircleCI: tutorials/integrations/circleci.md
          - Travis CI: tutorials/integrations/travis-ci.md
          - GitLab CI: tutorials/integrations/gitlab-ci.md
          - Bitbucket Pipelines: tutorials/integrations/bitbucket.md
          - AWS CodePipeline: tutorials/integrations/aws-codepipeline.md
          - AWS Security Hub: tutorials/integrations/aws-security-hub.md
          - Azure: tutorials/integrations/azure-devops.md
      - Kubernetes:
          - Cluster Scanning: tutorials/kubernetes/cluster-scanning.md
          - Kyverno: tutorials/kubernetes/kyverno.md
          - GitOps: tutorials/kubernetes/gitops.md
      - Signing:
          - Vulnerability Scan Record Attestation: tutorials/signing/vuln-attestation.md
      - Shell:
          - Completion: tutorials/shell/shell-completion.md
      - Additional Resources:
          - Additional Resources: tutorials/additional-resources/references.md
          - Community References: tutorials/additional-resources/community.md
          - CKS Reference: tutorials/additional-resources/cks.md
  - Docs:
      - Overview: docs/index.md
      - Target:
          Container Image: docs/target/container_image.md
          Filesystem: docs/target/filesystem.md
          Rootfs: docs/target/rootfs.md
          Git Repository: docs/target/git-repository.md
          Virtual Machine Image: docs/target/vm.md
          Kubernetes: docs/target/kubernetes.md
          AWS: docs/target/aws.md
          SBOM: docs/target/sbom.md
      - Vulnerability:
          - Scanning: docs/vulnerability/scanning.md
          - Detection:
              - OS Packages: docs/vulnerability/detection/os.md
              - Language-specific Packages: docs/vulnerability/detection/language.md
              - Data Sources: docs/vulnerability/detection/data-source.md
          - Database: docs/vulnerability/db.md
          - Examples:
              - Vulnerability Filtering: docs/vulnerability/examples/filter.md
              - Report Formats: docs/vulnerability/examples/report.md
              - Vulnerability DB: docs/vulnerability/examples/db.md
              - Cache: docs/vulnerability/examples/cache.md
              - Others: docs/vulnerability/examples/others.md
          - Languages:
              - Go: docs/vulnerability/languages/golang.md
              - Java: docs/vulnerability/languages/java.md
              - Node.js: docs/vulnerability/languages/nodejs.md
              - PHP: docs/vulnerability/languages/php.md
              - Python: docs/vulnerability/languages/python.md
              - Rust: docs/vulnerability/languages/rust.md
      - Misconfiguration:
          - Scanning: docs/misconfiguration/scanning.md
          - Policy:
              - Built-in Policies: docs/misconfiguration/policy/builtin.md
              - Exceptions: docs/misconfiguration/policy/exceptions.md
          - Custom Policies:
              - Overview: docs/misconfiguration/custom/index.md
              - Data: docs/misconfiguration/custom/data.md
              - Combine: docs/misconfiguration/custom/combine.md
              - Selectors: docs/misconfiguration/custom/selectors.md
              - Schemas: docs/misconfiguration/custom/schema.md
              - Testing: docs/misconfiguration/custom/testing.md
              - Debugging Policies: docs/misconfiguration/custom/debug.md
              - Examples: docs/misconfiguration/custom/examples.md
          - Options:
              - Policy: docs/misconfiguration/options/policy.md
              - Filtering: docs/misconfiguration/options/filter.md
              - Report Formats: docs/misconfiguration/options/report.md
              - Value Overrides: docs/misconfiguration/options/values.md
              - Others: docs/misconfiguration/options/others.md
      - Secret:
          - Scanning: docs/secret/scanning.md
          - Configuration: docs/secret/configuration.md
          - Examples: docs/secret/examples.md
      - License:
            - Scanning: docs/licenses/scanning.md
      - Compliance:
            - Reports:  docs/compliance/compliance.md
      - SBOM:
          - Overview: docs/sbom/index.md
          - CycloneDX: docs/sbom/cyclonedx.md
          - SPDX: docs/sbom/spdx.md
      - Attestation:
          - SBOM: docs/attestation/sbom.md
          - Cosign Vulnerability Scan Record: docs/attestation/vuln.md
          - SBOM Attestation in Rekor: docs/attestation/rekor.md
      - Advanced:
          - Modules: docs/advanced/modules.md
          - Plugins: docs/advanced/plugins.md
          - Air-Gapped Environment: docs/advanced/air-gap.md
          - Container Image:
              - Embed in Dockerfile: docs/advanced/container/embed-in-dockerfile.md
              - Unpacked container image filesystem: docs/advanced/container/unpacked-filesystem.md
              - Private Docker Registries:
                  - Overview: docs/advanced/private-registries/index.md
                  - Docker Hub: docs/advanced/private-registries/docker-hub.md
                  - AWS ECR (Elastic Container Registry): docs/advanced/private-registries/ecr.md
                  - GCR (Google Container Registry): docs/advanced/private-registries/gcr.md
                  - ACR (Azure Container Registry): docs/advanced/private-registries/acr.md
                  - Self-Hosted: docs/advanced/private-registries/self.md
      - References:
          - Customization:
              - Environment variables: docs/references/customization/envs.md
              - Config file: docs/references/customization/config-file.md
          - CLI:
              - Overview: docs/references/cli/trivy.md
              - AWS: docs/references/cli/trivy_aws.md
              - Config: docs/references/cli/trivy_config.md
              - Filesystem: docs/references/cli/trivy_filesystem.md
              - Image: docs/references/cli/trivy_image.md
              - Kubernetes: docs/references/cli/trivy_kubernetes.md
              - Module: docs/references/cli/trivy_module.md
              - Module Install: docs/references/cli/trivy_module_install.md
              - Module Uninstall: docs/references/cli/trivy_module_uninstall.md
              - Plugin: docs/references/cli/trivy_plugin.md
              - Plugin Info: docs/references/cli/trivy_plugin_info.md
              - Plugin Install: docs/references/cli/trivy_plugin_install.md
              - Plugin List: docs/references/cli/trivy_plugin_list.md
              - Plugin Run: docs/references/cli/trivy_plugin_run.md
              - Plugin Uninstall: docs/references/cli/trivy_plugin_uninstall.md
              - Plugin Update: docs/references/cli/trivy_plugin_update.md
              - Repository: docs/references/cli/trivy_repository.md
              - Rootfs: docs/references/cli/trivy_rootfs.md
              - SBOM: docs/references/cli/trivy_sbom.md
              - Server: docs/references/cli/trivy_server.md
              - Version: docs/references/cli/trivy_version.md
              - VM: docs/references/cli/trivy_vm.md
              
          - Modes:
              - Standalone: docs/references/modes/standalone.md
              - Client/Server: docs/references/modes/client-server.md
          - Troubleshooting: docs/references/troubleshooting.md
  - Ecosystem: 
    - Overview: ecosystem/index.md
    - CI/CD: ecosystem/cicd.md
    - IDE and Dev tools: ecosystem/ide.md
    - Production and Clouds: ecosystem/prod.md
    - Security Management: ecosystem/security.md
  - Contributing:
      - How to contribute:
          - Issues: community/contribute/issue.md
          - Pull Requests: community/contribute/pr.md
      - Maintainer:
          - Help Wanted: community/maintainer/help-wanted.md
          - Triage: community/maintainer/triage.md
theme:
  name: material
  language: "en"
  logo: imgs/logo-white.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  version:
    method: mike
    provider: mike

plugins:
  - search
  - macros

